//
// Created by wention on 2026/3/1.
//

#ifndef NVR_LOG_H
#define NVR_LOG_H

#define SPDLOG_ACTIVE_LEVEL 0

#include <spdlog/spdlog.h>

#define LOG_TRACE SPDLOG_TRACE
#define LOG_DEBUG SPDLOG_DEBUG
#define LOG_INFO SPDLOG_INFO
#define LOG_WARN SPDLOG_WARN
#define LOG_ERROR SPDLOG_ERROR
#define LOG_CRITICAL SPDLOG_CRITICAL

#define LOGGER_TRACE SPDLOG_LOGGER_TRACE
#define LOGGER_DEBUG SPDLOG_LOGGER_DEBUG
#define LOGGER_INFO SPDLOG_LOGGER_INFO
#define LOGGER_WARN SPDLOG_LOGGER_WARN
#define LOGGER_ERROR SPDLOG_LOGGER_ERROR
#define LOGGER_CRITICAL SPDLOG_LOGGER_CRITICAL

#endif //NVR_LOG_H
